version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      # Cài đặt SageMaker SDK và các thư viện cần thiết để chạy file pipeline.py
      - pip install --upgrade pip
      - pip install sagemaker boto3

  pre_build:
    commands:
      - echo "Checking environment and files..."
      # Kiểm tra xem file pipeline.py có tồn tại không trước khi chạy
      - ls -R
      # Bạn có thể thêm lệnh kiểm tra lỗi code (linting) ở đây nếu muốn
      # - flake8 pipelines/pipeline.py

  build:
    commands:
      - echo "Upserting SageMaker Pipeline..."
      # Chạy file python định nghĩa pipeline. 
      # File này sẽ chứa lệnh pipeline.upsert() để đẩy bản vẽ lên AWS.
      - python pipelines/pipeline.py

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pipeline has been updated. Check SageMaker Studio to see the new version."

artifacts:
  files:
    # Lưu lại file cấu hình hoặc kết quả kiểm tra nếu cần
    - '**/*'