phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies directly..."
      - pip install --upgrade pip
      # Cài đặt trực tiếp để chắc chắn không bị sót
      - pip install sagemaker tensorflow-cpu boto3
      # Thêm lệnh này để kiểm tra xem tensorflow đã có trong máy chưa
      - pip show tensorflow-cpu