version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Checking environment and files..."
      - ls -R

  build:
    commands:
      - echo "Upserting SageMaker Pipeline..."
      # Đảm bảo đường dẫn này khớp với cấu trúc folder trên GitHub của bạn
      - python pipeline/pipeline.py

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'